"""Add google_sub column to Users table

Revision ID: 514d506943b7
Revises: 
Create Date: 2024-08-02 11:21:33.432847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '514d506943b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('Roles',
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('role_name', sa.String(length=50), nullable=False),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('role_name')
    # )
    # op.create_index(op.f('ix_Roles_id'), 'Roles', ['id'], unique=False)
    # op.create_table('Permissions',
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('role_id', sa.Integer(), nullable=False),
    # sa.Column('table_name', sa.String(length=50), nullable=False),
    # sa.Column('create', sa.Boolean(), nullable=False),
    # sa.Column('read', sa.Boolean(), nullable=False),
    # sa.Column('update', sa.Boolean(), nullable=False),
    # sa.Column('delete', sa.Boolean(), nullable=False),
    # sa.ForeignKeyConstraint(['role_id'], ['Roles.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_Permissions_id'), 'Permissions', ['id'], unique=False)
    # op.create_table('Regulators',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('company_id', sa.Integer(), nullable=False),
    # sa.Column('regulator_name', sa.String(length=100), nullable=False),
    # sa.ForeignKeyConstraint(['company_id'], ['invester_manager.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_Regulators_id'), 'Regulators', ['id'], unique=False)
    # op.create_table('Users',
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('username', sa.String(length=50), nullable=False),
    # sa.Column('email', sa.String(length=50), nullable=False),
    # sa.Column('password_hash', sa.Text(), nullable=False),
    # sa.Column('role_id', sa.Integer(), nullable=False),
    # sa.Column('created_at', sa.DateTime(), nullable=False),
    # sa.Column('updated_at', sa.DateTime(), nullable=False),
    # sa.Column('google_sub', sa.String(length=255), nullable=True),
    # sa.ForeignKeyConstraint(['role_id'], ['Roles.id'], ),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('email'),
    # sa.UniqueConstraint('google_sub'),
    # sa.UniqueConstraint('username')
    # )
    # op.create_index(op.f('ix_Users_id'), 'Users', ['id'], unique=False)
    # op.create_table('Fund_jurisdiction',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('fund_id', sa.Integer(), nullable=False),
    # sa.Column('jurisdiction', sa.String(length=100), nullable=False),
    # sa.ForeignKeyConstraint(['fund_id'], ['fund_information.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_Fund_jurisdiction_id'), 'Fund_jurisdiction', ['id'], unique=False)
    # op.create_table('Service_provider',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('Fund_id', sa.Integer(), nullable=False),
    # sa.Column('Prime_Brokers', sa.String(length=50), nullable=True),
    # sa.Column('Custody', sa.String(length=50), nullable=True),
    # sa.Column('Legal', sa.String(length=50), nullable=True),
    # sa.Column('Audit', sa.String(length=50), nullable=True),
    # sa.Column('Admin', sa.String(length=50), nullable=True),
    # sa.Column('Trading_venues', sa.String(length=50), nullable=True),
    # sa.ForeignKeyConstraint(['Fund_id'], ['fund_information.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_Service_provider_id'), 'Service_provider', ['id'], unique=False)
    # op.drop_index('ix_Regulators_id', table_name='regulators')
    # op.drop_table('regulators')
    # op.drop_index('email', table_name='users')
    # op.drop_index('ix_Users_id', table_name='users')
    # op.drop_index('username', table_name='users')
    # op.drop_table('users')
    # op.drop_index('ix_Permissions_id', table_name='permissions')
    # op.drop_table('permissions')
    # op.drop_index('ix_Roles_id', table_name='roles')
    # op.drop_index('role_name', table_name='roles')
    # op.drop_table('roles')
    # op.drop_index('ix_Fund_jurisdiction_id', table_name='fund_jurisdiction')
    # op.drop_table('fund_jurisdiction')
    # op.drop_index('ix_Service_provider_id', table_name='service_provider')
    # op.drop_table('service_provider')
    # op.add_column('invester_manager', sa.Column('company_name', sa.String(), nullable=False))
    # op.add_column('invester_manager', sa.Column('overview', sa.Text(), nullable=True))
    # op.add_column('invester_manager', sa.Column('contact_person', sa.String(length=50), nullable=True))
    # op.add_column('invester_manager', sa.Column('contact_position', sa.String(length=50), nullable=True))
    # op.add_column('invester_manager', sa.Column('contact_email', sa.String(length=50), nullable=True))
    # op.add_column('invester_manager', sa.Column('website', sa.String(length=100), nullable=True))
    # op.add_column('invester_manager', sa.Column('phone_number', sa.String(length=15), nullable=True))
    # op.drop_index('Company_name', table_name='invester_manager')
    # op.drop_index('Website', table_name='invester_manager')
    # op.create_index(op.f('ix_invester_manager_id'), 'invester_manager', ['id'], unique=False)
    # op.create_unique_constraint(None, 'invester_manager', ['company_name'])
    # op.create_unique_constraint(None, 'invester_manager', ['website'])
    # op.drop_column('invester_manager', 'Contact_email')
    # op.drop_column('invester_manager', 'Contact_person')
    # op.drop_column('invester_manager', 'Phone_number')
    # op.drop_column('invester_manager', 'Website')
    # op.drop_column('invester_manager', 'Company_name')
    # op.drop_column('invester_manager', 'Contact_position')
    # op.drop_column('invester_manager', 'Overview')
    # op.alter_column('performance_returns', 'Yearly_returns',
    #            existing_type=mysql.DECIMAL(precision=10, scale=4),
    #            nullable=True)
    # op.alter_column('share_class', 'subscription_frequency',
    #            existing_type=mysql.VARCHAR(length=100),
    #            type_=sa.Integer(),
    #            existing_nullable=True)
        op.add_column('users',sa.Column('google_sub',sa.String(length=255),nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('share_class', 'subscription_frequency',
    #            existing_type=sa.Integer(),
    #            type_=mysql.VARCHAR(length=100),
    #            existing_nullable=True)
    # op.alter_column('performance_returns', 'Yearly_returns',
    #            existing_type=mysql.DECIMAL(precision=10, scale=4),
    #            nullable=False)
    # op.add_column('invester_manager', sa.Column('Overview', mysql.TEXT(), nullable=True))
    # op.add_column('invester_manager', sa.Column('Contact_position', mysql.VARCHAR(length=50), nullable=True))
    # op.add_column('invester_manager', sa.Column('Company_name', mysql.VARCHAR(length=50), nullable=False))
    # op.add_column('invester_manager', sa.Column('Website', mysql.VARCHAR(length=100), nullable=True))
    # op.add_column('invester_manager', sa.Column('Phone_number', mysql.VARCHAR(length=15), nullable=True))
    # op.add_column('invester_manager', sa.Column('Contact_person', mysql.VARCHAR(length=50), nullable=True))
    # op.add_column('invester_manager', sa.Column('Contact_email', mysql.VARCHAR(length=50), nullable=True))
    # op.drop_constraint(None, 'invester_manager', type_='unique')
    # op.drop_constraint(None, 'invester_manager', type_='unique')
    # op.drop_index(op.f('ix_invester_manager_id'), table_name='invester_manager')
    # op.create_index('Website', 'invester_manager', ['Website'], unique=True)
    # op.create_index('Company_name', 'invester_manager', ['Company_name'], unique=True)
    # op.drop_column('invester_manager', 'phone_number')
    # op.drop_column('invester_manager', 'website')
    # op.drop_column('invester_manager', 'contact_email')
    # op.drop_column('invester_manager', 'contact_position')
    # op.drop_column('invester_manager', 'contact_person')
    # op.drop_column('invester_manager', 'overview')
    # op.drop_column('invester_manager', 'company_name')
    # op.create_table('service_provider',
    # sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('Fund_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('Prime_Brokers', mysql.VARCHAR(length=50), nullable=True),
    # sa.Column('Custody', mysql.VARCHAR(length=50), nullable=True),
    # sa.Column('Legal', mysql.VARCHAR(length=50), nullable=True),
    # sa.Column('Audit', mysql.VARCHAR(length=50), nullable=True),
    # sa.Column('Admin', mysql.VARCHAR(length=50), nullable=True),
    # sa.Column('Trading_venues', mysql.VARCHAR(length=50), nullable=True),
    # sa.ForeignKeyConstraint(['Fund_id'], ['fund_information.id'], name='service_provider_ibfk_1'),
    # sa.PrimaryKeyConstraint('id'),
    # mysql_collate='utf8mb4_0900_ai_ci',
    # mysql_default_charset='utf8mb4',
    # mysql_engine='InnoDB'
    # )
    # op.create_index('ix_Service_provider_id', 'service_provider', ['id'], unique=False)
    # op.create_table('fund_jurisdiction',
    # sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('fund_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('jurisdiction', mysql.VARCHAR(length=100), nullable=False),
    # sa.ForeignKeyConstraint(['fund_id'], ['fund_information.id'], name='fund_jurisdiction_ibfk_1'),
    # sa.PrimaryKeyConstraint('id'),
    # mysql_collate='utf8mb4_0900_ai_ci',
    # mysql_default_charset='utf8mb4',
    # mysql_engine='InnoDB'
    # )
    # op.create_index('ix_Fund_jurisdiction_id', 'fund_jurisdiction', ['id'], unique=False)
    # op.create_table('roles',
    # sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('role_name', mysql.VARCHAR(length=50), nullable=False),
    # sa.PrimaryKeyConstraint('id'),
    # mysql_collate='utf8mb4_0900_ai_ci',
    # mysql_default_charset='utf8mb4',
    # mysql_engine='InnoDB'
    # )
    # op.create_index('role_name', 'roles', ['role_name'], unique=True)
    # op.create_index('ix_Roles_id', 'roles', ['id'], unique=False)
    # op.create_table('permissions',
    # sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('table_name', mysql.VARCHAR(length=50), nullable=False),
    # sa.Column('create', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    # sa.Column('read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    # sa.Column('update', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    # sa.Column('delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    # sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='permissions_ibfk_1'),
    # sa.PrimaryKeyConstraint('id'),
    # mysql_collate='utf8mb4_0900_ai_ci',
    # mysql_default_charset='utf8mb4',
    # mysql_engine='InnoDB'
    # )
    # op.create_index('ix_Permissions_id', 'permissions', ['id'], unique=False)
    # op.create_table('users',
    # sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    # sa.Column('email', mysql.VARCHAR(length=50), nullable=False),
    # sa.Column('password_hash', mysql.TEXT(), nullable=False),
    # sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('created_at', mysql.DATETIME(), nullable=False),
    # sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    # sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='users_ibfk_1'),
    # sa.PrimaryKeyConstraint('id'),
    # mysql_collate='utf8mb4_0900_ai_ci',
    # mysql_default_charset='utf8mb4',
    # mysql_engine='InnoDB'
    # )
    # op.create_index('username', 'users', ['username'], unique=True)
    # op.create_index('ix_Users_id', 'users', ['id'], unique=False)
    # op.create_index('email', 'users', ['email'], unique=True)
    # op.create_table('regulators',
    # sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('regulator_name', mysql.VARCHAR(length=100), nullable=False),
    # sa.ForeignKeyConstraint(['company_id'], ['invester_manager.id'], name='regulators_ibfk_1'),
    # sa.PrimaryKeyConstraint('id'),
    # mysql_collate='utf8mb4_0900_ai_ci',
    # mysql_default_charset='utf8mb4',
    # mysql_engine='InnoDB'
    # )
    # op.create_index('ix_Regulators_id', 'regulators', ['id'], unique=False)
    # op.drop_index(op.f('ix_Service_provider_id'), table_name='Service_provider')
    # op.drop_table('Service_provider')
    # op.drop_index(op.f('ix_Fund_jurisdiction_id'), table_name='Fund_jurisdiction')
    # op.drop_table('Fund_jurisdiction')
    # op.drop_index(op.f('ix_Users_id'), table_name='Users')
    # op.drop_table('Users')
    # op.drop_index(op.f('ix_Regulators_id'), table_name='Regulators')
    # op.drop_table('Regulators')
    # op.drop_index(op.f('ix_Permissions_id'), table_name='Permissions')
    # op.drop_table('Permissions')
    # op.drop_index(op.f('ix_Roles_id'), table_name='Roles')
    # op.drop_table('Roles')
    # ### end Alembic commands ###
         op.drop_column('users','google_sub')
